### ISSUE TITLE
New NPM release?

### ISSUE THREAD

**Issue by nothingismagick** [webpack-contrib/node-loader#15]
I noticed that the NPM release is very stale, do you intend to upgrade this?

**Comment by evilebottnawi** [comment]
Why? What is problem?

**Comment by nothingismagick** [comment]
It isn't a problem per sé as the latest dev version only has cosmetic changes to the code, it just got flagged by my security testing as being more than two years old.

**Comment by nothingismagick** [comment]
Also your CircleCI is about to go out of date:

```
Warning: Your project is using CircleCI 1.0 and will stop building on March 15, 2019. Update remaining projects to CircleCI 2.0 to continue building. Learn more.
```

**Comment by evilebottnawi** [comment]
No need release for fix it

**Comment by evilebottnawi** [comment]
The next version is migrated on github actions
