### ISSUE TITLE
Not working a 'node-iconv' modules

### ISSUE THREAD

**Issue by bitmapdata** [webpack-contrib/node-loader#2]
[node-iconv](https://github.com/bnoordhuis/node-iconv) project use a iconv.node

this code here `iconv/lib/iconv.js` at line 26 `bindings = require('../build/Release/iconv.node');` 

I replaced 
`bindings = require('../build/Release/iconv.node');` 
with 
`bindings = require('node!../build/Release/iconv.node');` 

also removed  at line 29 `bindings = require('../build/Debug/iconv.node');` because the file does not exist.

I have checked the `bindings` but value is `undefined`

**Comment by michael-ciniawsky** [comment]
@bitmapdata Still relevant? 😛 Can you please provde more info like `wepack.config.js` webpack/node/node-gyp version?

**Comment by suyuan1203** [comment]
No sure it's a bug of Webpack or node-iconv

node-iconv source code
```
var bindings;
try {
  bindings = require('../build/Release/iconv.node');
}
catch (e) {
  if (e.code !== 'MODULE_NOT_FOUND') throw e;
  bindings = require('../build/Debug/iconv.node');
}
```

Webpack tries to resolve both '../build/Release/iconv.node' and '../build/Debug/iconv.node', and fails to resolve '../build/Debug/iconv.node', because it doesn't exist.

**Comment by evilebottnawi** [comment]
I think better to do this:
```
{
  resolve: {
    alias: {
      './build/Debug/iconv.node$': path.resolve(
        __dirname,
        'node_modules/iconv/build/Release/iconv.node'
      ),
    },
  },
}
```

Just say to webpack that `Debug` is `Build` directory
