### ISSUE TITLE
Call dlopen to incorrect path

### ISSUE THREAD

**Issue by hajipy** [webpack-contrib/node-loader#21]
- Operating System: macOS 10.14.6
- Node Version: 12.14.0
- NPM Version: 6.13.4 (Yarn: 1.22.4)
- webpack Version: 4.43.0
- node-loader Version: 1.0.0

### Expected Behavior
call `dlopen` to `./dist/a795035e3333a278c24b6f3b6710e87f.node`

### Actual Behavior
call `dlopen` to `//a795035e3333a278c24b6f3b6710e87f.node`

### Code

```js
// webpack.config.js
const path = require("path");

module.exports = {
    entry: "./src/index.js",
    output: {
        path: path.resolve(__dirname, "./dist"),
        filename: "bundle.js"
    },
    target: "node",
    module: {
        rules: [
            {
                test: /\.node$/,
                loader: "node-loader",
            }
        ]
    }
};
```

```js
// src/index.js
import keytar from "keytar";

(async () => {
    await keytar.getPassword("service", "account");
})();
```

### How Do We Reproduce?
Please checkout following repository.
https://github.com/hajipy/node-loader-test

**Comment by evilebottnawi** [comment]
Please read carefull docs https://github.com/webpack-contrib/node-loader#getting-started:
```
 node: {
    __dirname: false,
  },
```

**Comment by hajipy** [comment]
Thanks for the answer.
My problem has been successfully solved.

**Comment by tchakabam** [comment]
@evilebottnawi That being said, your docs could be written more clearly in that sense, I have overseen it too at first sight :) 

Otherwise, thanks for the great work on this, keep it up 👍
