### ISSUE TITLE
Failing to load .node file after upgrading to 1.0.0 from 0.6.0

### ISSUE THREAD

**Issue by grit96** [webpack-contrib/node-loader#23]
- Operating System: macOS 10.15.4
- Node Version: v12.4.0
- NPM Version: 6.9.0
- webpack Version: 4.43.0
- node-loader Version: 1.0.0

### Expected Behavior

After upgrading to 1.0.0 `.node` file would be loaded without error.

### Actual Behavior

After upgrading to 1.0.0 `.node` file is not loaded with the following error `Uncaught Error: node-loader: Error: ENOENT, renderer/1c4a1496ce4a9c4a7b5b692ccaba69d9.node not found in node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar`.

It works fine when I downgrade back to 0.6.0.

### Code

```js
// webpack.config.js
{
  target: 'electron-renderer',
  module: {
    rules: [
      {
        test: /\.node$/,
        use: require.resolve('node-loader')
      }
    ]
  },
  node: {
    __dirname: false
  }
}
```

**Comment by evilebottnawi** [comment]
@grit96 Please create reproducible test repo and do not ignore `How Do We Reproduce?`, I will reopen issue after you update the issue template
