### ISSUE TITLE
 process.dlopen: The specified module could not be found

### ISSUE THREAD

**Issue by eng-dibo** [webpack-contrib/node-loader#32]
I use `node-loader` to load `.node` files with webpack, however, it generates the output files as expected in `dist` folder.

```
// dist/file.js

__webpack_require__.p =""
process.dlopen(module, __dirname + "/" + __webpack_require__.p + "sharp.node");
```

and sharp.node exists in the same dir.
but I got this error

```
node-loader:
Error: The specified module could not be found.
D:\Downloads\__projects\dev\NodeJs\@eng-dibo\ngx\dist\ sharp.node
```

the path determined in the error message is correct and exists

minimal reproduction: https://github.com/lovell/sharp/issues/2517#issuecomment-767703678

**Comment by alexander-akait** [comment]
`D:\Downloads\__projects\dev\NodeJs\@eng-dibo\ngx\dist\.node` is invalid path, please create reproducible test repo and use the issue template

**Comment by eng-dibo** [comment]
> `D:\Downloads\__projects\dev\NodeJs\@eng-dibo\ngx\dist\.node` is invalid path, please create reproducible test repo and use the issue template

just typo, updated

**Comment by alexander-akait** [comment]
Please create reproducible test repo, I can't help you without additional information

**Comment by eng-dibo** [comment]
repo:
https://github.com/eng-dibo/ngx

the base webpack config file is located in the workspace's root.

the issue occures when you build:server of the project 'cms'
to do that, run the following command from the workspace's root.

```
npm run build:server:dev --prefix projects/cms
```


additional info:
I installed sharp on windows 8 with this cmd:
```
npm i sharp
```

I will try the following, may this help
```
npm install --arch=x64 --platform=linux sharp
```

**Comment by alexander-akait** [comment]
Why you use `node-loader` for `browser` target? It will not work, this loader only for node or electron

**Comment by alexander-akait** [comment]
Anyway `npm run build:server:dev --prefix projects/cms` doesn't this error (linux/ubuntu)

**Comment by alexander-akait** [comment]
I think sharp doesn't support windows@8

**Comment by eng-dibo** [comment]
> I think sharp doesn't support windows@8

it does, because I already used it before in the same laptop.

**Comment by alexander-akait** [comment]
If you don't have `.node` file, it means you really don't have it, there is no magic

**Comment by alexander-akait** [comment]
We use very simple logic https://github.com/webpack-contrib/node-loader/blob/master/src/index.js#L32

**Comment by eng-dibo** [comment]
I have .node file, but the problem is that it fails to be loaded by `process.dlopen`

you can see this file in
dist/cms/core/server/[hash].node

**Comment by eng-dibo** [comment]
> We use very simple logic https://github.com/webpack-contrib/node-loader/blob/master/src/index.js#L32

yes, that exactly what I see in the output file. but as the title suggests it is seem that the issue is caused when executing this function.

**Comment by alexander-akait** [comment]
This function from Node.js, we can't control execution here https://nodejs.org/api/process.html#process_process_dlopen_module_filename_flags

**Comment by alexander-akait** [comment]
Run this function on file from dist, without webpack, just using simple Node.js script and look at result

**Comment by eng-dibo** [comment]
![New Bitmap Image](https://user-images.githubusercontent.com/57308531/103790540-04026580-504a-11eb-89fd-1816397393f4.jpg)

**Comment by alexander-akait** [comment]
No problems with loader as you can see

**Comment by eng-dibo** [comment]
so, what are your suggestions?

**Comment by alexander-akait** [comment]
Something wrong with sharp on windows 8, I can't even reproduce it on virtual machine, update windows...

**Comment by eng-dibo** [comment]
> Something wrong with sharp on windows 8, I can't even reproduce it on virtual machine, update windows...

thank you, @alexander-akait for your efforts <3

**Comment by alexander-akait** [comment]
Can you try it on other machine under windows?

**Comment by eng-dibo** [comment]
minimal reproduction: https://github.com/lovell/sharp/issues/2517#issuecomment-767703678

**Comment by alexander-akait** [comment]
Why do you use `externals: [nodeExternals()]`? It keep all modules from `node_modules` inside
