### ISSUE TITLE
not work in vue.config.js

### ISSUE THREAD

**Issue by shaomingming008** [webpack-contrib/node-loader#36]
![image](https://user-images.githubusercontent.com/22759207/107304679-86a09980-6abc-11eb-8309-c0f3710ed155.png)
![image](https://user-images.githubusercontent.com/22759207/107304739-a8018580-6abc-11eb-8b4d-52e2948a1826.png)
node:14.15.4
npm:6.14.10
electron:11.2.2

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect the time of other developers
