### ISSUE TITLE
concat directory separators instead of "/" to make it work on Windows

### ISSUE THREAD

**Issue by Gohan** [webpack-contrib/node-loader#39]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `node-loader@1.0.2` for the project I'm working on.

The problem:

node-loader won't work well with Quasar-framework + electron + webpack process flow on Windows:

the generate code: `process.dlopen(module, __dirname + "/" + __webpack_public_path__ + ${JSON.stringify(name)}${typeof options.flags !== 'undefined' ? `, ${JSON.stringify(options.flags)}` : ''});` fails with  "/" on windows platform.

I tried to use `require("path").sep` to make the loader more platform sensitive for Windows compability

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/node-loader/dist/index.js b/node_modules/node-loader/dist/index.js
index b57fb73..fef0365 100644
--- a/node_modules/node-loader/dist/index.js
+++ b/node_modules/node-loader/dist/index.js
@@ -31,7 +31,7 @@ function loader(content) {
   this.emitFile(name, content);
   return `
 try {
-  process.dlopen(module, __dirname + "/" + __webpack_public_path__ + ${JSON.stringify(name)}${typeof options.flags !== 'undefined' ? `, ${JSON.stringify(options.flags)}` : ''});
+  process.dlopen(module, __dirname + require("path").sep + __webpack_public_path__ + ${JSON.stringify(name)}${typeof options.flags !== 'undefined' ? `, ${JSON.stringify(options.flags)}` : ''});
 } catch (error) {
   throw new Error('node-loader:\\n' + error);
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by alexander-akait** [comment]
PR welcome

**Comment by Gohan** [comment]
> PR welcome

#40 
pending licence/cla Pending — Contributor License Agreement is not signed yet.

don't know how to signed.. 

![image](https://user-images.githubusercontent.com/212567/112878401-7b500e80-90fa-11eb-972a-c4a74f8248bc.png)

**Comment by alexander-akait** [comment]
You need use the same email in commits

**Comment by Gohan** [comment]
> You need use the same email in commits

Has pass the PR check

**Comment by alexander-akait** [comment]
Fixed
