### ISSUE TITLE
vue.config.js not resolve

### ISSUE THREAD

**Issue by shaomingming008** [webpack-contrib/node-loader#43]
- Operating System:Windows 10
- Node Version:v14.15.5
- NPM Version:6.14.11
- webpack Version:4.46.0
- node-loader Version:1.0.2

### Expected Behavior

worked in vue.config.js

### Actual Behavior

do not worked

### Code

![107304679-86a09980-6abc-11eb-8309-c0f3710ed155](https://user-images.githubusercontent.com/22759207/116526517-422ed800-a90c-11eb-90f2-c6fc56c6ca46.png)
![107304739-a8018580-6abc-11eb-8b4d-52e2948a1826](https://user-images.githubusercontent.com/22759207/116526525-43f89b80-a90c-11eb-9c49-05d957811823.png)

**Comment by alexander-akait** [comment]
Please open an issue in `vue-cli`, we can't fix it here, sorry
