### ISSUE TITLE
README Typo?

### ISSUE THREAD

**Issue by timfish** [webpack-contrib/node-loader#50]
The readme currently says:

> ⚠ node-loader only works on the `node`/`electron-main`/`electron-main` targets.

It says `electron-main` twice. Should it be `electron-preload` or `electron-renderer` or both?

**Comment by alexander-akait** [comment]
Feel free to send a fix

**Comment by timfish** [comment]
I would do a PR but I'm asking a question:

> Should it be `electron-preload` or `electron-renderer` or both?

It says it only works with specific targets and I don't know why there is this limitation so I don't know which targets it's supposed to work with!

**Comment by snitin315** [comment]
> It says it only works with specific targets and I don't know why there is this limitation so I don't know which targets it's supposed to work with!

non-web `node` related targets.
