### ISSUE TITLE
 TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by zhuosheng-li** [webpack-contrib/node-loader#52]
- Operating System:
- Node Version: v14.15.1
- NPM Version: 6.14.11
- webpack Version: 5.6.0
- node-loader Version: 2.0.0

### Actual Behavior
yarn build   

### Code

```js
Module build failed (from ./node_modules/node-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
```

```js
// additional code, HEY YO remove this block if you don't need it
```

**Comment by alexander-akait** [comment]
You need webpack v5 to use the latest version node-loader, please read changelog
