### ISSUE TITLE
Electron use node-loader parse .node error?

### ISSUE THREAD

**Issue by chenweihan** [webpack-contrib/node-loader#74]
ERROR  Failed to compile with 1 errors                                                                                                                                                                                  

 error  in ./src/hello/hello.node

Module build failed (from ./node_modules/node-loader/dist/cjs.js):
TypeError: this.getOptions is not a function
    at Object.loader (C:\desk\nest-frontend-desk\node_modules\node-loader\dist\index.js:22:24)

 @ ./src/background.js 8:0-39 10:12-17
 @ multi ./src/background.js

Hi, I use Electron and Calling the Node file. but I found this bug.

I replace the following code, which used to work fine and  I can call functions in Hello. node.
//const options = this.getOptions(_options.default);
const options = _options.default;

where is getOptions function???

**Comment by alexander-akait** [comment]
You use webpack v4, you need to use lower version if you need to support webpack v5
